//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesDE.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.ProductInOrder = new HashSet<ProductInOrder>();
        }
    
        public int Id { get; set; }
        public string Article { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public int PickUpPointId { get; set; }
        public int UserId { get; set; }
        public string ReceiptCode { get; set; }
        public int StatusId { get; set; }
    
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual PickUpPoint PickUpPoint { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductInOrder> ProductInOrder { get; set; }
    }
}
